In [1]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split

iris=load_iris()

print("IRIS FEATURES/TARGET NAMES:", iris.target_names)
for i in range(len(iris.target_names)):
     print("[{0}]:[{1}]".format(i,iris.target_names[i]))

IRIS FEATURES/TARGET NAMES: ['setosa' 'versicolor' 'virginica']
[0]:[setosa]
[1]:[versicolor]
[2]:[virginica]


In [21]:
print("\n IRIS DATA :\n",iris.data)
print("\n Target: \n",iris.target)


 IRIS DATA :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.

In [3]:
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target, random_state=0)

In [22]:
print("\n X TRAIN \n", X_train)
print("\n X TEST \n", X_test)
print("\n Y TRAIN \n", y_train)
print("\n Y TEST \n", y_test)


 X TRAIN 
 [[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]


In [5]:
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [6]:
x_new = np.array([[5, 2.9, 1, 0.2]])
print("X_NEW Array \n",x_new)
prediction = model.predict(x_new)

print("\nPredicted target value: {}".format(prediction))
print("Predicted feature name: {}".format(iris.target_names[prediction]))

X_NEW Array 
 [[5.  2.9 1.  0.2]]

Predicted target value: [0]
Predicted feature name: ['setosa']


In [30]:
i=1
x= X_test[i]
abc = np.array([x])
print("\n abc array(from X_test) \n",abc)

for i in range(len(X_test)):
 x = X_test[i]
 abc = np.array([x])
 prediction = model.predict(abc)
 print("Actual: {0} {1}, Predicted: {2}{3}".format(y_test[i],iris.target_names[y_test[i]],prediction,iris.target_names[prediction]))


 abc array(from X_test) 
 [[6.  2.2 4.  1. ]]
Actual: virginica 2, Predicted: [2]['virginica']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: setosa 0, Predicted: [0]['setosa']
Actual: virginica 2, Predicted: [2]['virginica']
Actual: setosa 0, Predicted: [0]['setosa']
Actual: virginica 2, Predicted: [2]['virginica']
Actual: setosa 0, Predicted: [0]['setosa']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: virginica 2, Predicted: [2]['virginica']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: setosa 0, Predicted: [0]['setosa']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: versicolor 1, Predicted: [1]['versicolor']
Actual: setosa 0, Predicted: [0]['setosa']
Actual: setosa 0, Predicted: [0]

In [26]:
print("Accuracy Score: {:.2f}".format(model.score(X_test, y_test)))

Accuracy Score: 0.97
